### ISSUE TITLE
반공변성 이해를 이렇게 해보았는데, 피드백 있으면 남겨주세요.

### ISSUE THREAD

**Issue by wizardeye** [mustaine80/Scala#1]
먼저 Int 를 받아 Int 를 반환하는 함수객체를 정의하고
var f: Int => Int = (i: Int) => i + 1

우리가 만든 코드는 위의 f 함수값을 사용한다고 생각하는 예를 들면
var foo = List [ Int ]  (1,2,3) map f
// 2,3,4

이 경우 함수 f 를 사용할 때 Int(1,2,3)을 넘겨야 하는 것을 잘 알고 있음. 왜냐하면 함수 f 를 그렇게 정의했기 때문

그런데, f 값이 외부에서 넘어오는 값으로 변경될 경우, 해당 코드를 아래처럼 작성했다면
(a: Any) => 0 /// 실제 이런 코드는 없겠지만...

그래서, f = (a: Any) => 0 이렇게 값이 변경되면
foo 의 값은 List [ Int ]( 0, 0, 0) 이 됨

이 때, Int 입력이 Any 에 할당이 되는데, 이것은 LSP 에 부합됨.
따라서, 반공변성이 Function Trait 에서는(Function1[-T1, +R]) 당연함.

UIObject 예제를 살펴보았는데, 실전에서는 그런 모양새가 나올 것 같고, 다만 LSP 측면에서 자연스럽게 이해가 안되었는데 위 예제를 만들면서 해소되었음.

**Comment by nFramework** [comment]
위 내용 설명은 이해를 했습니다.

저도 이부분에 대해서 찾아봤습니다.

확실히 C#2.0에서 Array (확실히 Collection 다루는 이슈부터) 처리부터 시작되었습니다.

즉, C#2.0에서 4.0까지 가는 사이 Collection의 일반화 문제를 다루기 위한(이 부분은 찾아 보세요)

몇몇 문법들이 나타났고, 공변성과 반공변성을 지원하기 위해서(이 표현이 맞는것 같습니다.)

문법들이 변하고 있었습니다.(최종 C#의 in, out 키워드입니다.)

일단 위키피디아 영문을 보면 이렇습니다.

covariance: converting from wider to narrower
contravariance: converting from narrower to wider

즉, 공변성은 상위에서 하위로 변하는 것(자식타입치환)
반공변성은 하위에서 상위로 변하는 것(부모타입치환)

우리가 이부분이 많이 헷갈렸는데

공변성 == 반환타입호환성
반공변성 == 파라미터환성

이해하시면 편할 것같습니다.

"Scala Variance : Covariant, Invariant and Contravariant" 원문을 보면

변성은 파라미터화된 타입의 상속관계를 정의하는 것으로 나와있습니다.

파라미터화된 타입이 저는 개인적으로 이해를 잘 못했는데

Lits[T]의 구체화된 타입 예를들어, List[Int], List[Anyval] 등을 파라미터화된 타입이라고 합니다.
다시 말해 변성은 이들 파라미터화된 타입 즉, List[Int], List[Anyval] 등의 상속관계를 나타내는 성질입니다.

여기에서 공변성, 반공변성을 알아야 하는데

말씀드렸듯이, 변성은 파라미터화된 타입의 상속구조라고 했습니다.

공변성을 이렇게 정의합니다.

S가 T의 서브타입이면, List[S]는 List[T]의 서브타입니다.

우리가 알고 있듯이 저렇게 되도록 할려면 스칼라는 List[+T] 라고 씁니다.

즉, List[+T]라고 쓰면 위의 공변성 정의가 되는 것입니다.

다시 말해서, List[S]는 List[T]의 서브타입이므로, 이것이 LSP를 따른다고 보시면 됩니다.

LSP가 "상위가 하위를 후킹할 수 있다" 이니까

공변성을 대입하면 List[T]가 List[S]를 후킹할 수 있다로 보시면 됩니다.

따라서, List[T] = List[S] 같은 좌상 우하가 성립이 됩니다. 이런 경우는 값을 가져오는 경우이고

다시 말해 Get, Out키워드, 리턴타입 호환 이런것과 연관됩니다.

반대로 반공변성은

S가 T의 서브타입이면, List[T]는 List[S]의 서브타입이다.

이렇게 이해하고 공변성에서 설명해놓은 대로 하시면 됩니다.

List[T]는 List[S]의 서브타입이므로, 이것이 LSP를 따른다고 보시면 됩니다.

LSP가 "상위가 하위를 후킹할 수 있다" 이니까

반공변성을 대입하면 List[S]가 List[T]를 후킹할 수 있다로 보시면 됩니다.

따라서, List[S] = List[T]가 되는 것입니다.

이런 경우는 파라미터화된 타입의 값을 상위에 쓸 때 적용됩니다.

다시 말해, Put, In키워드, 파라미터 호환 이런것과 연관됩니다.


공변과 반공변은 원리이고 이것을 언어에서 지원하기 위한 방법들이 있는 것이며,
C#은 그 모호함을 없애기 위해서 In(반공변), Out(공변)만들어 냈습니다.

따라서 값을 리턴할 땐 Out, 값을 파라미터로 받을 땐 In 키워를 씁니다.

물론 이것은 변성에 관한 것 즉,  파라미터화된 타입을 기준으로 보시면 됩니다.

**Comment by nFramework** [comment]
그래서 값을 가져오는 Source는 공변, 값을 써야되는 destination은 반공변으로 정의합니다.
